[env:m5stamp-pico]
platform = espressif32
board = m5stamp-pico
framework = arduino
monitor_speed = 115200
upload_speed = 921600
extra_scripts = post:provision.py

lib_deps =
    h2zero/NimBLE-Arduino
    https://github.com/ESP32Async/ESPAsyncWebServer

board_build.partitions = partitions.csv

board_build.arduino.loop_stack_size = 8192

build_flags =
    -DCONFIG_BT_NIMBLE_ROLE_BROADCASTER=0
    -DCONFIG_BT_NIMBLE_ROLE_PERIPHERAL=0
    -DCONFIG_BT_NIMBLE_ROLE_OBSERVER=1
    -DCONFIG_BT_NIMBLE_ROLE_CENTRAL=1
    -DCONFIG_BT_NIMBLE_MAX_CONNECTIONS=1
    -DCONFIG_BT_NIMBLE_MAX_BONDS=3

build_src_flags =
    !bash version.sh

[env:ota]
extends = env:m5stamp-pico
upload_protocol = espota
upload_port = airbridge
upload_flags = --auth=${sysenv.AIRBRIDGE_OTA_PASS}
